# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customers_3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ustomers_3.proto\"\x8e\x04\n\x13\x43ustomers_3_Message\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0c\n\x04guid\x18\x03 \x01(\t\x12\x10\n\x08isActive\x18\x04 \x01(\x08\x12\x0f\n\x07\x62\x61lance\x18\x05 \x01(\x02\x12\x0f\n\x07picture\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\r\x12\x10\n\x08\x65yeColor\x18\x08 \x01(\t\x12\x0c\n\x04name\x18\t \x01(\t\x12\x0e\n\x06gender\x18\n \x01(\t\x12\x0f\n\x07\x63ompany\x18\x0b \x01(\t\x12\r\n\x05\x65mail\x18\x0c \x01(\t\x12\r\n\x05phone\x18\r \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x0e \x01(\t\x12\r\n\x05\x61\x62out\x18\x0f \x01(\t\x12\x12\n\nregistered\x18\x10 \x01(\t\x12\x10\n\x08latitude\x18\x11 \x01(\x02\x12\x11\n\tlongitude\x18\x12 \x01(\x02\x12\x0c\n\x04tags\x18\x13 \x03(\t\x12-\n\x07\x66riends\x18\x14 \x03(\x0b\x32\x1c.Customers_3_Message.Friends\x12\'\n\x04\x66oes\x18\x15 \x03(\x0b\x32\x19.Customers_3_Message.Foes\x12\x10\n\x08greeting\x18\x16 \x01(\t\x12\x15\n\rfavoriteFruit\x18\x17 \x01(\t\x1a#\n\x07\x46riends\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a \n\x04\x46oes\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t')



_CUSTOMERS_3_MESSAGE = DESCRIPTOR.message_types_by_name['Customers_3_Message']
_CUSTOMERS_3_MESSAGE_FRIENDS = _CUSTOMERS_3_MESSAGE.nested_types_by_name['Friends']
_CUSTOMERS_3_MESSAGE_FOES = _CUSTOMERS_3_MESSAGE.nested_types_by_name['Foes']
Customers_3_Message = _reflection.GeneratedProtocolMessageType('Customers_3_Message', (_message.Message,), {

  'Friends' : _reflection.GeneratedProtocolMessageType('Friends', (_message.Message,), {
    'DESCRIPTOR' : _CUSTOMERS_3_MESSAGE_FRIENDS,
    '__module__' : 'customers_3_pb2'
    # @@protoc_insertion_point(class_scope:Customers_3_Message.Friends)
    })
  ,

  'Foes' : _reflection.GeneratedProtocolMessageType('Foes', (_message.Message,), {
    'DESCRIPTOR' : _CUSTOMERS_3_MESSAGE_FOES,
    '__module__' : 'customers_3_pb2'
    # @@protoc_insertion_point(class_scope:Customers_3_Message.Foes)
    })
  ,
  'DESCRIPTOR' : _CUSTOMERS_3_MESSAGE,
  '__module__' : 'customers_3_pb2'
  # @@protoc_insertion_point(class_scope:Customers_3_Message)
  })
_sym_db.RegisterMessage(Customers_3_Message)
_sym_db.RegisterMessage(Customers_3_Message.Friends)
_sym_db.RegisterMessage(Customers_3_Message.Foes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMERS_3_MESSAGE._serialized_start=22
  _CUSTOMERS_3_MESSAGE._serialized_end=548
  _CUSTOMERS_3_MESSAGE_FRIENDS._serialized_start=479
  _CUSTOMERS_3_MESSAGE_FRIENDS._serialized_end=514
  _CUSTOMERS_3_MESSAGE_FOES._serialized_start=516
  _CUSTOMERS_3_MESSAGE_FOES._serialized_end=548
# @@protoc_insertion_point(module_scope)
